# cargo-deny: supply-chain gate for the ~600 crates in Cargo.lock.
# Only `advisories` and `sources` run in CI today; `licenses` and `bans` are
# configured but not yet enforced, so enabling them cannot turn CI red without
# someone first reviewing the backlog they report.

[advisories]
version = 2
yanked = "deny"
ignore = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[licenses]
version = 2
confidence-threshold = 0.9
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"
